version: "3.9"

services:
  db:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - TZ=Europe/London
      - MYSQL_DATABASE=woodshop #optional
      - MYSQL_USER=MYSQL_USER #optional
      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
    restart: "always"
    ports:
      - 3308:3306
    volumes:
      - ./db/data:/config
  api:
    image: woodshopapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:5000
      - 5001:5000
    depends_on:
      - db
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080
    depends_on:
      - db
