version: "3.9"

services:
  db:
    # image: "hypriot/rpi-mysql"
    image: "mysql:8"
    environment:
      MYSQL_DATABASE: 'woodshop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    restart: "always"
    ports:
      - 3308:3306
    volumes:
      - ./db/data:/var/lib/mysql
  # api:
  #   image: woodshopapi
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - ASPNETCORE_URLS=http://+:5000
  #     - ASPNETCORE_ENVIRONMENT=Docker
  #   ports:
  #     - 5000:5000
  #     - 5001:5000
  #   depends_on:
  #     - db
  #   volumes:
  #     - ~/.vsdbg:/remote_debugger:rw