// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DataContext;

namespace Project.Migrations
{
    [DbContext(typeof(WoodshopContext))]
    [Migration("20210415133716_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("efac1814-c014-4a61-beac-70914fee2447"),
                            Name = "Oregon 7x15",
                            Price = 5.0099999999999998,
                            Thickness = 7.0,
                            Width = 15.0
                        },
                        new
                        {
                            ProductId = new Guid("5ed018fe-3c32-4575-b840-2e3eaa4cfee9"),
                            Name = "Oregon 7x18",
                            Price = 4.6200000000000001,
                            Thickness = 7.0,
                            Width = 18.0
                        },
                        new
                        {
                            ProductId = new Guid("0ed3a879-9779-49c0-8e60-ce7c69bfdb57"),
                            Name = "Pannelatten",
                            Price = 0.29999999999999999,
                            Thickness = 2.3999999999999999,
                            Width = 3.2000000000000002
                        },
                        new
                        {
                            ProductId = new Guid("a1b155dd-58af-4a4f-b39a-8c0a6cc4d7f0"),
                            Name = "Stoflatten",
                            Price = 0.22,
                            Thickness = 2.0,
                            Width = 2.2999999999999998
                        },
                        new
                        {
                            ProductId = new Guid("2c1894c0-5716-4bcb-9728-f6b4f905b162"),
                            Name = "RND gedrenkt",
                            Price = 0.84999999999999998,
                            Thickness = 2.5,
                            Width = 10.0
                        },
                        new
                        {
                            ProductId = new Guid("cbb9efdb-7266-4399-8143-509a08baa442"),
                            Name = "RND ongeschaafd",
                            Price = 0.60999999999999999,
                            Thickness = 2.0,
                            Width = 10.0
                        },
                        new
                        {
                            ProductId = new Guid("1b01d0a1-d4b1-48e9-bfb8-290e1ce21865"),
                            Name = "Merantiplaten",
                            Price = 4.4500000000000002,
                            Thickness = 0.35999999999999999,
                            Width = 122.0
                        },
                        new
                        {
                            ProductId = new Guid("30d2a068-4911-4778-9b8b-73b42b03b948"),
                            Name = "CDX platen",
                            Price = 6.5599999999999996,
                            Thickness = 1.8,
                            Width = 122.0
                        },
                        new
                        {
                            ProductId = new Guid("11cb3725-712d-427b-95bd-4a3d6d39d620"),
                            Name = "OBS platen",
                            Price = 3.9700000000000002,
                            Thickness = 1.2,
                            Width = 59.0
                        },
                        new
                        {
                            ProductId = new Guid("3fe0990f-da7c-4eaa-ad74-767bb53c4dce"),
                            Name = "Meubelplaten wit",
                            Price = 5.6200000000000001,
                            Thickness = 1.0,
                            Width = 20.0
                        },
                        new
                        {
                            ProductId = new Guid("c6ab1756-b8fc-4c97-bdaa-9d101c03c0d8"),
                            Name = "Gipsplaten",
                            Price = 2.6400000000000001,
                            Thickness = 0.90000000000000002,
                            Width = 0.0
                        },
                        new
                        {
                            ProductId = new Guid("4ba85fce-ba82-4e82-a78a-6d7f60fb94ec"),
                            Name = "Plafondlatten",
                            Price = 0.56999999999999995,
                            Thickness = 2.2000000000000002,
                            Width = 4.5
                        },
                        new
                        {
                            ProductId = new Guid("cf4e75d9-8680-4426-b7fb-b021c14c3d07"),
                            Name = "CLS",
                            Price = 0.98999999999999999,
                            Thickness = 3.7999999999999998,
                            Width = 5.7999999999999998
                        },
                        new
                        {
                            ProductId = new Guid("c0beab4e-5cfa-457e-9592-9841ac584fbe"),
                            Name = "Terrasplanken tali",
                            Price = 6.3499999999999996,
                            Thickness = 2.5,
                            Width = 14.5
                        },
                        new
                        {
                            ProductId = new Guid("242295fc-67e1-4879-9988-9c2c5124f151"),
                            Name = "Thermowood",
                            Price = 6.1500000000000004,
                            Thickness = 63.0,
                            Width = 150.0
                        },
                        new
                        {
                            ProductId = new Guid("ca52d51f-3f20-436a-bc94-952ab27fb133"),
                            Name = "Tali kepers",
                            Price = 2.8100000000000001,
                            Thickness = 40.0,
                            Width = 55.0
                        });
                });

            modelBuilder.Entity("Project.Models.Unit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Unit");

                    b.HasData(
                        new
                        {
                            UnitId = new Guid("c208378d-b3d4-47dd-8509-51a13232f494"),
                            Desc = "Lopende meter",
                            Name = "lm"
                        },
                        new
                        {
                            UnitId = new Guid("c0377bf7-27a7-402f-a41b-5f38e22e1c04"),
                            Desc = "Vierkante meter",
                            Name = "m²"
                        },
                        new
                        {
                            UnitId = new Guid("01d4f0bf-50bd-448a-808a-1d3ddb1e63b3"),
                            Desc = "Kubieke meter",
                            Name = "m³"
                        },
                        new
                        {
                            UnitId = new Guid("d077172a-a255-48ab-b08a-ea7bdd3a14c8"),
                            Desc = "Stuk",
                            Name = "st"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
