// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DataContext;

namespace Project.Migrations
{
    [DbContext(typeof(WoodshopContext))]
    partial class WoodshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("8b6f35a6-75bb-4b64-acf7-d8674019ad05"),
                            Name = "Oregon 7x15",
                            Price = 5.0099999999999998,
                            Thickness = 7.0,
                            Width = 15.0
                        },
                        new
                        {
                            ProductId = new Guid("abadf9f4-de1f-47a0-81bf-52edf0f8fa42"),
                            Name = "Oregon 7x18",
                            Price = 4.6200000000000001,
                            Thickness = 7.0,
                            Width = 18.0
                        },
                        new
                        {
                            ProductId = new Guid("ffb573dc-7c71-44df-96dc-7b8cb17d1fa2"),
                            Name = "Pannelatten",
                            Price = 0.29999999999999999,
                            Thickness = 2.3999999999999999,
                            Width = 3.2000000000000002
                        },
                        new
                        {
                            ProductId = new Guid("d3300290-30cc-41ac-8519-665257d31cb5"),
                            Name = "Stoflatten",
                            Price = 0.22,
                            Thickness = 2.0,
                            Width = 2.2999999999999998
                        },
                        new
                        {
                            ProductId = new Guid("ceabaf33-912f-43fd-bca0-4fbe7293be63"),
                            Name = "RND gedrenkt",
                            Price = 0.84999999999999998,
                            Thickness = 2.5,
                            Width = 10.0
                        },
                        new
                        {
                            ProductId = new Guid("dc527628-8d7b-4fa2-811a-af7485fc5c40"),
                            Name = "RND ongeschaafd",
                            Price = 0.60999999999999999,
                            Thickness = 2.0,
                            Width = 10.0
                        },
                        new
                        {
                            ProductId = new Guid("8e069572-6397-406e-a7bd-5145fed3d5c3"),
                            Name = "Merantiplaten",
                            Price = 4.4500000000000002,
                            Thickness = 0.35999999999999999,
                            Width = 122.0
                        },
                        new
                        {
                            ProductId = new Guid("63224a77-3d77-4694-a6a3-88d8c2f331ad"),
                            Name = "CDX platen",
                            Price = 6.5599999999999996,
                            Thickness = 1.8,
                            Width = 122.0
                        },
                        new
                        {
                            ProductId = new Guid("abd63f4e-b3cc-45c3-a5ca-3fec43a9c048"),
                            Name = "OBS platen",
                            Price = 3.9700000000000002,
                            Thickness = 1.2,
                            Width = 59.0
                        },
                        new
                        {
                            ProductId = new Guid("183ffada-40d8-4368-88ce-9568db16d612"),
                            Name = "Meubelplaten wit",
                            Price = 5.6200000000000001,
                            Thickness = 1.0,
                            Width = 20.0
                        },
                        new
                        {
                            ProductId = new Guid("becb5a2c-a47e-40c0-8b11-816e65b03cf9"),
                            Name = "Gipsplaten",
                            Price = 2.6400000000000001,
                            Thickness = 0.90000000000000002,
                            Width = 0.0
                        },
                        new
                        {
                            ProductId = new Guid("320ff00c-78a4-4525-89fb-4f4ba7a0ad6b"),
                            Name = "Plafondlatten",
                            Price = 0.56999999999999995,
                            Thickness = 2.2000000000000002,
                            Width = 4.5
                        },
                        new
                        {
                            ProductId = new Guid("d878e6e2-7ff9-45e6-b5b4-4f8556f288fe"),
                            Name = "CLS",
                            Price = 0.98999999999999999,
                            Thickness = 3.7999999999999998,
                            Width = 5.7999999999999998
                        },
                        new
                        {
                            ProductId = new Guid("83763a83-ebaf-486e-9137-04ebbcd230a3"),
                            Name = "Terrasplanken tali",
                            Price = 6.3499999999999996,
                            Thickness = 2.5,
                            Width = 14.5
                        },
                        new
                        {
                            ProductId = new Guid("8d941eaf-8acf-4a51-9218-ed89646b5306"),
                            Name = "Thermowood",
                            Price = 6.1500000000000004,
                            Thickness = 63.0,
                            Width = 150.0
                        },
                        new
                        {
                            ProductId = new Guid("31c75690-ce1d-4d58-82c1-c48e0b42c194"),
                            Name = "Tali kepers",
                            Price = 2.8100000000000001,
                            Thickness = 40.0,
                            Width = 55.0
                        });
                });

            modelBuilder.Entity("Project.Models.Unit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = new Guid("490a11b4-d282-4e7b-b0fa-89ee96045751"),
                            Desc = "Lopende meter",
                            Name = "lm"
                        },
                        new
                        {
                            UnitId = new Guid("f82de43e-179e-4bc8-9d9e-1d3768e95665"),
                            Desc = "Vierkante meter",
                            Name = "m²"
                        },
                        new
                        {
                            UnitId = new Guid("00019668-e681-4f91-96b6-96840ae96dbc"),
                            Desc = "Kubieke meter",
                            Name = "m³"
                        },
                        new
                        {
                            UnitId = new Guid("4d80392b-1204-4191-95dd-c3b39f8bff0a"),
                            Desc = "Stuk",
                            Name = "st"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
